server:
  port: 8761
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone:  http://127.0.0.1:8762/eureka,http://127.0.0.1:${server.port}/eureka
  instance:
    # 指定本节点的IP
    ip-address: 127.0.0.1
    # 通过IP方式注册
    prefer-ip-address: true
    # 配置实力编号
    instance-id:  ${eureka.instance.ip-address}:${server.port}:@project.version@

  server:
    # 心跳检测功能
    enable-self-preservation: true
    # 集群节点之间读取超时时间。单位：毫秒
    peer-node-read-timeout-ms: 5000
    # 集群节点之间连接超时时间。单位：毫秒
    peer-node-connect-timeout-ms: 15000
spring:
  application:
    name: eureka-service